apiVersion: v1
kind: Pod
metadata:
  name: fleetman-queue
  labels:
    app: fleetman-queue
spec:
  containers:
    - name: fleetman-queue
      image: richardchesterwood/k8s-fleetman-queue:release1
      

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue-service

spec:
  #This defines which ports are going to be represented by this service
  # The service becomes a network endpoint for wither other services
  #or maybe external users to connect to
  selector:
    app: fleetman-queue

  ports:
    - port: 8161
      nodePort: 30011

  type: NodePort
  
  


