apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp

spec:
  #This defines which ports are going to be represented by this service
# The service becomes a network endpoint for wither other services
#or maybe external users to connect to
  selector:
    app: webapp
    release: "0-5"
  
  ports:
    - port: 80
      nodePort: 30080
      
  type: NodePort